name: Postman API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Client Docker Image
        run: |
          docker build -t demo-client ./client

      - name: Build Server Docker Image
        run: |
          docker build -t demo-server ./server

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Newman
        run: |
          npm install -g newman

      - name: Check Newman Version
        run: |
          newman --version

      - name: Run Postman Collection with Newman
        run: |
          newman run postman/344_kamal.json
