name: Postman API Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # 3. Install project dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Start Node.js server
      - name: Start server
        run: |
          npm start &
          sleep 5

      # 5. Check API/server
      - name: Check API
        run: |
          curl http://localhost:3000

      # 6. Install Newman
      - name: Install Newman
        run: npm install -g newman

      # 7. Check Newman
      - name: Check Newman Version
        run: newman --version

      # 8. Run Postman collection
      - name: Run Postman Collection
        run: |
          newman run postman/344_kamal.json
